/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

/**
 *
 * @author Dell
 */
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.event.*;
import javax.swing.Timer;
import java.util.*;
public class HomeScreenView extends javax.swing.JFrame {

    /**
     * Creates new form HomeScreen
     */
   controllerClass obj;
   String playerOne;
   String playerTwo;
   
    public HomeScreenView() {
        initComponents();
        setSize(624, 364);

        setLocationRelativeTo(null);
        
        obj=new controllerClass();
        
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
     
        
       
    }
    
    void getPlayers(){
        playerOne=player1.getText();
        playerTwo=player2.getText();
        
        System.out.println("PLAYERS: "+playerOne+playerTwo);
        
        if (playerOne.equals("")) {
            playerOne = "Player One";
        }
        if (playerTwo.equals("")) {
            playerTwo = "Player Two";
        }
        System.out.println("PLAYERS: "+playerOne+playerTwo);
        
        obj.addUser(playerOne);
        obj.addUser(playerTwo);
        
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        instructionsButton = new javax.swing.JButton();
        playGameButton = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        player1 = new javax.swing.JTextField();
        player2 = new javax.swing.JTextField();
        scoreBoardButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setText("PLAYER 1:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 120, 90, 20);

        instructionsButton.setBackground(new java.awt.Color(255, 255, 255));
        instructionsButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        instructionsButton.setForeground(new java.awt.Color(204, 0, 0));
        instructionsButton.setText("HOW TO PLAY?");
        instructionsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                instructionsButtonActionPerformed(evt);
            }
        });
        getContentPane().add(instructionsButton);
        instructionsButton.setBounds(230, 270, 220, 23);

        playGameButton.setBackground(new java.awt.Color(255, 255, 255));
        playGameButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        playGameButton.setForeground(new java.awt.Color(204, 0, 0));
        playGameButton.setText("PLAY");
        playGameButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                playGameButtonActionPerformed(evt);
            }
        });
        getContentPane().add(playGameButton);
        playGameButton.setBounds(230, 190, 220, 23);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/image (6).gif"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(80, 30, 450, 70);

        jLabel5.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 51, 51));
        jLabel5.setText("PLAYER 2:");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(160, 150, 70, 17);

        player1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        player1.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(player1);
        player1.setBounds(280, 120, 165, 20);

        player2.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        player2.setForeground(new java.awt.Color(204, 0, 0));
        getContentPane().add(player2);
        player2.setBounds(280, 150, 165, 20);

        scoreBoardButton.setBackground(new java.awt.Color(255, 255, 255));
        scoreBoardButton.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        scoreBoardButton.setForeground(new java.awt.Color(204, 0, 0));
        scoreBoardButton.setText("SCORE BOARD");
        scoreBoardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                scoreBoardButtonActionPerformed(evt);
            }
        });
        getContentPane().add(scoreBoardButton);
        scoreBoardButton.setBounds(230, 230, 220, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/image1.gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(160, 190, 29, 23);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/image1.gif"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(160, 230, 29, 23);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/image1.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(160, 270, 29, 23);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/image6.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(-6, -20, 670, 420);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoreBoardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_scoreBoardButtonActionPerformed
        // TODO add your handling code here:
      //  this.dispose();
        ScoreBoardView object=new ScoreBoardView();
        object.setVisible(true);
    }//GEN-LAST:event_scoreBoardButtonActionPerformed

    private void instructionsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_instructionsButtonActionPerformed
        // TODO add your handling code here:
     //   this.dispose();
        HowToPlayView object=new HowToPlayView();
        object.setVisible(true);
    }//GEN-LAST:event_instructionsButtonActionPerformed

    private void playGameButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_playGameButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        getPlayers();
        GameView object=new GameView(playerOne,playerTwo);
        object.setVisible(true);
    }//GEN-LAST:event_playGameButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HomeScreenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HomeScreenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HomeScreenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HomeScreenView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HomeScreenView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton instructionsButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JButton playGameButton;
    private javax.swing.JTextField player1;
    private javax.swing.JTextField player2;
    private javax.swing.JButton scoreBoardButton;
    // End of variables declaration//GEN-END:variables
}
