/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

/**
 *
 * @author Dell
 */

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.event.*;
import javax.swing.Timer;
import java.util.*;

public class HowToPlayView extends javax.swing.JFrame {

    /**
     * Creates new form HowToPlayView
     */
    public HowToPlayView() {
        initComponents();
        setSize(624, 364);

        setLocationRelativeTo(null);
        jScrollPane1.setBorder(null);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/image (8).gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(66, 26, 488, 93);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(0, 0, 0));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(204, 0, 0));
        jTextArea1.setRows(5);
        jTextArea1.setText("The objective of Tic Tac Toe is to get three in a row. You play on a three by \nthree game board. The first player is known as X and the second is O. Players \nalternate placing Xs and Os on the game board until either opponent has three in\na row or all nine squares are filled. X always goes first, and in the event that \nno one has three in a row, the stalemate is called a draw.");
        jTextArea1.setBorder(null);
        jTextArea1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTextArea1.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(66, 150, 488, 90);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/icons8-question-mark-80.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 110, 60, 70);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/icons8-question-mark-80.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(-20, -10, 60, 70);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/icons8-question-mark-80.gif"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(70, 100, 60, 70);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/icons8-question-mark-80.gif"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(580, 20, 60, 70);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/icons8-question-mark-80.gif"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(520, 100, 60, 70);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/icons8-question-mark-80.gif"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(570, 210, 60, 70);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/icons8-question-mark-80.gif"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 280, 60, 70);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/icons8-question-mark-80.gif"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(60, 250, 60, 70);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/icons8-question-mark-80.gif"))); // NOI18N
        getContentPane().add(jLabel10);
        jLabel10.setBounds(140, 310, 60, 70);

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/icons8-question-mark-80.gif"))); // NOI18N
        getContentPane().add(jLabel11);
        jLabel11.setBounds(-20, 140, 60, 70);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/image6.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(0, 0, 630, 380);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(HowToPlayView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(HowToPlayView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(HowToPlayView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(HowToPlayView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new HowToPlayView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
