/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tictactoe;

/**
 *
 * @author Dell
 */

import java.awt.Color;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Graphics2D;
import java.awt.geom.Line2D;
import java.awt.geom.Rectangle2D;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.EmptyBorder;
import java.awt.event.*;
import javax.swing.Timer;
import java.util.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.JTableHeader;

public class ScoreBoardView extends javax.swing.JFrame {

    /**
     * Creates new form ScoreBoardView
     */
    public ScoreBoardView() {
        initComponents();
        setSize(624, 364);
        
        JTableHeader head=new JTableHeader();
        setLocationRelativeTo(null);
        jScrollPane1.setBorder(null);
        addRowToTable();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
    }
    
    ArrayList<controllerClass> LoadAllUsers() {
        controllerClass obj = new controllerClass();
        return obj.LoadAllUsers();
    }
    
     public void addRowToTable() {
      //  System.out.println("gointo");
        ArrayList<controllerClass> user = LoadAllUsers();
        DefaultTableModel model = (DefaultTableModel) scoreTable.getModel();
        Object rowdata[] = new Object[2];
        for (int i = 0; i < user.size(); i++) {
            rowdata[0] = user.get(i).username;
         //   System.out.println(rowdata[0]+"name check table");
            rowdata[1] = user.get(i).wins;
          //  System.out.println(rowdata[1]+"wins check table");
            model.addRow(rowdata);
        }
        scoreTable.setModel(model);  
  //  System.out.println(model.getRowCount()+"checkkk rows");//returns 1
  //  System.out.println(model.getColumnCount()+"checks columns");//returns 0
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        scoreTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/image (7).gif"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(120, 0, 397, 70);

        scoreTable.setFont(new java.awt.Font("Tempus Sans ITC", 1, 12)); // NOI18N
        scoreTable.setForeground(new java.awt.Color(255, 51, 51));
        scoreTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Player Name", "Number of Wins"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scoreTable.setGridColor(new java.awt.Color(255, 51, 51));
        scoreTable.setOpaque(false);
        scoreTable.setSelectionBackground(new java.awt.Color(204, 0, 0));
        jScrollPane1.setViewportView(scoreTable);
        if (scoreTable.getColumnModel().getColumnCount() > 0) {
            scoreTable.getColumnModel().getColumn(0).setResizable(false);
            scoreTable.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(110, 120, 397, 138);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/image4.gif"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 80, 160, 130);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/image4.gif"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(440, 210, 160, 130);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tictactoe/image6.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 640, 370);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ScoreBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ScoreBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ScoreBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ScoreBoardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ScoreBoardView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable scoreTable;
    // End of variables declaration//GEN-END:variables
}
